services:
    het-mysql-db:
        image: mysql:8.0
        container_name: het-mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: home_energy_tracker
        ports:
            - "3307:3306"
        volumes:
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - db_data:/var/lib/mysql
            - db_data:/var/log/mysql

volumes:
  db_data:
